extends: eslint-config-cheminfo
env:
  browser: true
  amd: true
  es6: true

rules:
  # Disable those for now
  no-console: 1
  curly: 0
  eqeqeq: 0
  camelcase: 0
  no-unused-vars: 0
  no-redeclare: 0
  no-fallthrough: 0
  no-self-assign: 0
  array-callback-return: 0
  no-cond-assign: 0
  no-multiple-empty-lines: 0
  space-unary-ops: 0
  no-unsafe-negation: 0

  comma-dangle:
    - 2
    - "never"
  no-negated-in-lhs: 2
  valid-typeof: 2
  no-extra-label: 2
  no-lone-blocks: 2
  no-multi-spaces: 2
  no-new-wrappers: 2
  no-unused-expressions: 2
  no-with: 2
  no-delete-var: 2
  no-label-var: 2
  no-shadow-restricted-names: 2
  no-undef-init: 2
  no-undef: 2
  array-bracket-spacing: 2
  brace-style:
    - 2
    - "1tbs"
    - {allowSingleLine: true}
  consistent-this:
    - 2
    - "that"
  new-parens: 2
  no-array-constructor: 2
  no-mixed-spaces-and-tabs: 2
  no-new-object: 2
  no-spaced-func: 2
  no-trailing-spaces:
    - 2
    - {skipBlankLines: true}

globals:
  setImmediate: false,
  escape: false,
  unescape: false,
  $: false,
  jQuery: false,
  DataObject: false,
  DataArray: false,
  DataString: false,
  DataNumber: false,
  DataBoolean: false
