extends: eslint-config-cheminfo
env:
  browser: true
  amd: true
  es6: true

rules:
  # Disable those for now
  no-console: 1
  curly: 0
  eqeqeq: 0
  camelcase: 0
  no-unused-vars: 0
  no-redeclare: 0
  array-callback-return: 0

  no-multi-spaces: 2
  brace-style:
    - 2
    - "1tbs"
    - {allowSingleLine: true}
  consistent-this:
    - 2
    - "that"
  no-trailing-spaces:
    - 2
    - {skipBlankLines: true}

globals:
  setImmediate: false,
  escape: false,
  unescape: false,
  $: false,
  jQuery: false,
  DataObject: false,
  DataArray: false,
  DataString: false,
  DataNumber: false,
  DataBoolean: false
