extends: eslint-config-cheminfo
env:
  browser: true
  amd: true
  es6: true
parserOptions:
  ecmaVersion: 2021

rules:
  # Disable those for now
  no-console: 1
  no-eval: 0
  curly: 0
  eqeqeq: 0
  camelcase: 0
  no-unused-vars: 0
  no-redeclare: 0
  array-callback-return: 0
  consistent-return: 0
  prefer-spread: 0
  default-case: 0
  no-loop-func: 0
  no-implicit-globals: 2
  no-prototype-builtins: 0
  no-empty-function: 0
  one-var: 0
  no-multi-spaces: 2
  prefer-rest-params: 0
  brace-style:
    - 2
    - '1tbs'
    - { allowSingleLine: true }
  consistent-this:
    - 2
    - 'that'
  no-trailing-spaces:
    - 2
    - { skipBlankLines: true }
  import/no-dynamic-require: off

globals:
  setImmediate: false
  escape: false
  unescape: false
  $: false
  jQuery: false
  DataObject: false
  DataArray: false
  DataString: false
  DataNumber: false
  DataBoolean: false
