reject:
  # Now ESM with multiple exports, but we rely on the default export.
  # Also, delay@5 cannot be parsed by the esprima version used by requirejs
  - delay
  # Now ESM and depends on top-level await.
  - tempfile
  # Version 7 had breaking changes not worth the effort.
  - conventional-changelog
  # Version 2.0.3 made a breaking change with whitespaces: https://github.com/slab/quill/issues/4509
  - quill