var wN="3",xN="Any",yN="Aromatic",zN="Nonring",AN="Reset",BN="Ring";function CN(){CN=s;DN=new Xn(Rc,new EN)}function EN(){}r(191,188,{},EN);_.Oc=function(a){vv();XJ(this,a.b,FN(a.a.a,a.a.a.ob.selectedIndex))};_.Rc=function(){return DN};var DN;function GN(a,b){if(0>b||b>=a.ob.options.length)throw new xs;}function FN(a,b){GN(a,b);return a.ob.options[b].value}function HN(){this.ob=$doc.createElement("select");this.ob[Tc]="gwt-ListBox"}r(336,314,oh,HN);function IN(){IN=s}
function JN(a,b){if(null==b)throw new zp("Missing message: awt.103");var c=-1,d,e,f;f=a.lc.a.ob;e=$doc.createElement(ff);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function KN(){IN();uv.call(this);new ki;this.lc=new LN((vv(),this))}r(401,388,{89:1,91:1,98:1,110:1,116:1},KN);_.Xd=function(){return zv(this.lc,this)};
_.ke=function(){return(null==this.ic&&(this.ic=gv(this)),this.ic)+va+this.tc+va+this.uc+va+this.qc+Ag+this.gc+(this.pc?l:",hidden")+",current="+FN(this.lc.a,this.lc.a.ob.selectedIndex)};function MN(){vJ.call(this,7)}r(414,1,kh,MN);function NN(a){xJ.call(this,a,0)}r(419,388,Ph,NN);r(545,543,Gh);_.Kc=function(){!this.a.Hb?this.a.Hb=new ON(this.a):this.a.Hb.lc.c.gb?LK(this.a.Hb.lc.c):SJ(this.a.Hb)};function PN(a,b){HI(b)==a.a?Z(b,(ew(),nw)):Z(b,a.a)}
function QN(a){var b,c,d,e;e=l;d=!1;HI(RN)!=a.a?(e=ta,d=!0):HI(SN)!=a.a?(e="!#6",d=!0):HI(TN)!=a.a?(Z(UN,(ew(),nw)),Z(XN,nw),Z(YN,nw),Z(ZN,nw),e="F,Cl,Br,I"):(b=HI($N)!=a.a,c=HI(aO)!=a.a,HI(bO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),HI(cO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),HI(dO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),HI(eO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),HI(fO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),HI(UN)!=a.a&&(e+="F,"),HI(XN)!=a.a&&(e+="Cl,"),HI(YN)!=a.a&&(e+="Br,"),HI(ZN)!=a.a&&(e+="I,"),
gC(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=mc:c?e=ob:(Z(RN,(ew(),nw)),e=ta)));b=l;d&&HI($N)!=a.a&&(b+=";a");d&&HI(aO)!=a.a&&(b+=";A");HI(gO)!=a.a&&(b+=";R");HI(hO)!=a.a&&(b+=";!R");HI(RN)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=iO.lc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=jO.lc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);HI(kO)!=a.a&&(e="~");HI(lO)!=a.a&&(e=eb);HI(mO)!=a.a&&(e=nb);HI(nO)!=a.a&&(e="!@");kx(a.e.lc,e)}
function oO(a){pO(a);qO(a);var b=iO.lc.a;GN(b,0);b.ob.options[0].selected=!0;b=jO.lc.a;GN(b,0);b.ob.options[0].selected=!0;Z($N,a.a);Z(aO,a.a);Z(gO,a.a);Z(hO,a.a);Z(iO,a.a);Z(jO,a.a);rO(a)}function pO(a){Z(bO,a.a);Z(cO,a.a);Z(dO,a.a);Z(eO,a.a);Z(fO,a.a);Z(UN,a.a);Z(XN,a.a);Z(YN,a.a);Z(ZN,a.a)}function qO(a){Z(RN,a.a);Z(SN,a.a);Z(TN,a.a)}function rO(a){Z(kO,a.a);Z(lO,a.a);Z(mO,a.a);Z(nO,a.a);a.b=!1}
function ON(a){oJ.call(this,"Atom/Bond Query");this.i=new hJ(this.$f());Yv(this.q,new VJ(this));this.a=(ly(),ny);this.c=a;this.d||(a=jv(a),this.d=new zJ(a),RJ(this.d,-150,10));this.j=this.d;Iv(this,new MN);Z(this,this.a);a=new Nv;Iv(a,new Ew(0,3,1));$(a,new NN("Atom type :"),null);RN=new hJ(xN);SN=new hJ("Any except C");TN=new hJ("Halogen");$(a,RN,null);$(a,SN,null);$(a,TN,null);$(this,a,null);a=new Nv;Iv(a,new Ew(0,3,1));$(a,new xJ("Or select one or more from the list :",0),null);$(this,a,null);
a=new Nv;Iv(a,new Ew(0,3,1));bO=new hJ(sb);cO=new hJ(Lb);dO=new hJ(Rb);eO=new hJ(Yb);fO=new hJ(Sb);UN=new hJ(Ab);XN=new hJ(vb);YN=new hJ(rb);ZN=new hJ(Gb);$(a,bO,null);$(a,cO,null);$(a,dO,null);$(a,eO,null);$(a,fO,null);$(a,UN,null);$(a,XN,null);$(a,YN,null);$(a,ZN,null);$(this,a,null);a=new Nv;Iv(a,new Ew(0,3,1));iO=new KN;JN(iO,xN);JN(iO,Ya);JN(iO,$a);JN(iO,db);JN(iO,wN);$(a,new NN("Number of hydrogens :  "),null);$(a,iO,null);$(this,a,null);a=new Nv;Iv(a,new Ew(0,3,1));jO=new KN;JN(jO,xN);JN(jO,
Ya);JN(jO,$a);JN(jO,db);JN(jO,wN);JN(jO,"4");JN(jO,"5");JN(jO,"6");$(a,new xJ("Number of connections :",0),null);$(a,jO,null);$(a,new xJ(" (H's don't count.)",0),null);$(this,a,null);a=new Nv;Iv(a,new Ew(0,3,1));$(a,new NN("Atom is :"),null);$N=new hJ(yN);$(a,$N,null);aO=new hJ("Nonaromatic");$(a,aO,null);gO=new hJ(BN);$(a,gO,null);hO=new hJ(zN);$(a,hO,null);$(this,a,null);a=new Nv;Z(a,uw(HI(this)));Iv(a,new Ew(0,3,1));$(a,new NN("Bond is :"),null);kO=new hJ(xN);$(a,kO,null);lO=new hJ(yN);$(a,lO,
null);mO=new hJ(BN);$(a,mO,null);nO=new hJ(zN);$(a,nO,null);$(this,a,null);a=new Nv;Iv(a,new Ew(1,3,1));this.e=new jx(ta,20);$(a,this.e,null);$(a,new hJ(AN),null);$(a,this.i,null);$(this,a,null);this.lc&&qJ(this.lc.c,!1);nJ(this,!1);pO(this);qO(this);rO(this);Z($N,this.a);Z(aO,this.a);Z(gO,this.a);Z(hO,this.a);Z(iO,this.a);Z(jO,this.a);PN(this,RN);mJ(this);a=this.j;TJ(this.lc.c,a.a,a.b);!iv(this)&&QI(this);LI(this)}r(555,537,lF,ON);
_._f=function(a,b){var c;H(b,AN)?(oO(this),PN(this,RN),QN(this)):E(a.f,88)?(rO(this),gq(a.f)===gq(RN)?(pO(this),qO(this)):gq(a.f)===gq(SN)?(pO(this),qO(this)):gq(a.f)===gq(TN)?(pO(this),qO(this)):gq(a.f)===gq(gO)?Z(hO,this.a):gq(a.f)===gq(hO)?(Z(gO,this.a),Z($N,this.a)):gq(a.f)===gq($N)?(Z(aO,this.a),Z(hO,this.a)):gq(a.f)===gq(aO)?Z($N,this.a):gq(a.f)===gq(kO)||gq(a.f)===gq(lO)||gq(a.f)===gq(mO)||gq(a.f)===gq(nO)?(oO(this),this.b=!0):qO(this),PN(this,a.f),QN(this)):E(a.f,89)&&(rO(this),c=a.f,0==c.lc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(ew(),nw)),QN(this));107!=this.c.e&&(this.c.e=107,Sv(this.c));return!0};_.ag=function(){return tm(this.e.lc.a.ob,rg)};_.bg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var RN=_.e=null,kO=null,SN=null,$N=null,lO=null,YN=null,bO=null,jO=null,iO=null,XN=null,UN=null,TN=null,ZN=null,cO=null,aO=null,hO=null,nO=null,dO=null,fO=null,gO=null,mO=null,eO=null;function LN(a){qE();sE.call(this);this.a=new HN;es(this.a,new sO(this,a),(CN(),CN(),DN))}r(601,599,{},LN);_.Ee=function(){return this.a};
_.a=null;function sO(a,b){this.a=a;this.b=b}r(602,1,{},sO);_.a=null;_.b=null;Y(555);Y(401);Y(601);Y(602);Y(336);Y(191);y(eF)(3);