var yP="3",zP="Any",AP="Aromatic",BP="Nonring",CP="Reset",DP="Ring";function GP(){GP=r;HP=new ep(cd,new IP)}function IP(){}q(215,212,{},IP);_.Sc=function(a){Fx();ZL(this,a.b,JP(a.a.a,a.a.a.ob.selectedIndex))};_.Vc=function(){return HP};var HP;function KP(a,b){if(0>b||b>=a.ob.options.length)throw new wu;}function JP(a,b){KP(a,b);return a.ob.options[b].value}function LP(){ov();this.ob=$doc.createElement("select");this.ob[ed]="gwt-ListBox"}q(361,339,Xh,LP);function MP(){MP=r}
function NP(a,b){if(null==b)throw new Wq("Missing message: awt.103");var c=-1,d,e,f;f=a.lc.a.ob;e=$doc.createElement(pf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function OP(){MP();Ex.call(this);new yi;this.lc=new PP((Fx(),this))}q(428,415,{90:1,92:1,99:1,111:1,117:1},OP);_.ee=function(){return Jx(this.lc,this)};
_.te=function(){return(null==this.ic&&(this.ic=qx(this)),this.ic)+xa+this.tc+xa+this.uc+xa+this.qc+Og+this.gc+(this.pc?l:",hidden")+",current="+JP(this.lc.a,this.lc.a.ob.selectedIndex)};function QP(){wL.call(this,7)}q(441,1,Wh,QP);function RP(a){yL.call(this,a,0)}q(446,415,zh,RP);q(583,581,Yh);_.Oc=function(){!this.a.Hb?this.a.Hb=new SP(this.a):this.a.Hb.lc.c.gb?NM(this.a.Hb.lc.c):UL(this.a.Hb)};function TP(a,b){IK(b)==a.a?Z(b,(py(),yy)):Z(b,a.a)}
function UP(a){var b,c,d,e;e=l;d=!1;IK(VP)!=a.a?(e=va,d=!0):IK(WP)!=a.a?(e="!#6",d=!0):IK(XP)!=a.a?(Z(YP,(py(),yy)),Z(ZP,yy),Z($P,yy),Z(aQ,yy),e="F,Cl,Br,I"):(b=IK(bQ)!=a.a,c=IK(cQ)!=a.a,IK(dQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),IK(eQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),IK(fQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),IK(gQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),IK(hQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),IK(YP)!=a.a&&(e+="F,"),IK(ZP)!=a.a&&(e+="Cl,"),IK($P)!=a.a&&(e+="Br,"),IK(aQ)!=a.a&&(e+="I,"),
JE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=rc:c?e=rb:(Z(VP,(py(),yy)),e=va)));b=l;d&&IK(bQ)!=a.a&&(b+=";a");d&&IK(cQ)!=a.a&&(b+=";A");IK(iQ)!=a.a&&(b+=";R");IK(jQ)!=a.a&&(b+=";!R");IK(VP)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=kQ.lc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=lQ.lc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);IK(mQ)!=a.a&&(e="~");IK(nQ)!=a.a&&(e=hb);IK(oQ)!=a.a&&(e=qb);IK(pQ)!=a.a&&(e="!@");BL(a.e,e)}
function qQ(a){rQ(a);sQ(a);var b=kQ.lc.a;KP(b,0);b.ob.options[0].selected=!0;b=lQ.lc.a;KP(b,0);b.ob.options[0].selected=!0;Z(bQ,a.a);Z(cQ,a.a);Z(iQ,a.a);Z(jQ,a.a);Z(kQ,a.a);Z(lQ,a.a);tQ(a)}function rQ(a){Z(dQ,a.a);Z(eQ,a.a);Z(fQ,a.a);Z(gQ,a.a);Z(hQ,a.a);Z(YP,a.a);Z(ZP,a.a);Z($P,a.a);Z(aQ,a.a)}function sQ(a){Z(VP,a.a);Z(WP,a.a);Z(XP,a.a)}function tQ(a){Z(mQ,a.a);Z(nQ,a.a);Z(oQ,a.a);Z(pQ,a.a);a.b=!1}
function SP(a){pL.call(this,"Atom/Bond Query");this.i=new iL(this.jg());iy(this.q,new XL(this));this.a=(MA(),OA);this.c=a;this.d||(a=tx(a),this.d=new AL(a),TL(this.d,-150,10));this.j=this.d;Sx(this,new QP);Z(this,this.a);a=new Xx;Sx(a,new Py(0,3,1));$(a,new RP("Atom type :"),null);VP=new iL(zP);WP=new iL("Any except C");XP=new iL("Halogen");$(a,VP,null);$(a,WP,null);$(a,XP,null);$(this,a,null);a=new Xx;Sx(a,new Py(0,3,1));$(a,new yL("Or select one or more from the list :",0),null);$(this,a,null);
a=new Xx;Sx(a,new Py(0,3,1));dQ=new iL(wb);eQ=new iL(Rb);fQ=new iL(Vb);gQ=new iL(cc);hQ=new iL(Wb);YP=new iL(Gb);ZP=new iL(Ab);$P=new iL(vb);aQ=new iL(Kb);$(a,dQ,null);$(a,eQ,null);$(a,fQ,null);$(a,gQ,null);$(a,hQ,null);$(a,YP,null);$(a,ZP,null);$(a,$P,null);$(a,aQ,null);$(this,a,null);a=new Xx;Sx(a,new Py(0,3,1));kQ=new OP;NP(kQ,zP);NP(kQ,$a);NP(kQ,db);NP(kQ,gb);NP(kQ,yP);$(a,new RP("Number of hydrogens :  "),null);$(a,kQ,null);$(this,a,null);a=new Xx;Sx(a,new Py(0,3,1));lQ=new OP;NP(lQ,zP);NP(lQ,
$a);NP(lQ,db);NP(lQ,gb);NP(lQ,yP);NP(lQ,"4");NP(lQ,"5");NP(lQ,"6");$(a,new yL("Number of connections :",0),null);$(a,lQ,null);$(a,new yL(" (H's don't count.)",0),null);$(this,a,null);a=new Xx;Sx(a,new Py(0,3,1));$(a,new RP("Atom is :"),null);bQ=new iL(AP);$(a,bQ,null);cQ=new iL("Nonaromatic");$(a,cQ,null);iQ=new iL(DP);$(a,iQ,null);jQ=new iL(BP);$(a,jQ,null);$(this,a,null);a=new Xx;Z(a,Fy(IK(this)));Sx(a,new Py(0,3,1));$(a,new RP("Bond is :"),null);mQ=new iL(zP);$(a,mQ,null);nQ=new iL(AP);$(a,nQ,
null);oQ=new iL(DP);$(a,oQ,null);pQ=new iL(BP);$(a,pQ,null);$(this,a,null);a=new Xx;Sx(a,new Py(1,3,1));this.e=new tz(va,20);$(a,this.e,null);$(a,new iL(CP),null);$(a,this.i,null);$(this,a,null);this.lc&&rL(this.lc.c,!1);oL(this,!1);rQ(this);sQ(this);tQ(this);Z(bQ,this.a);Z(cQ,this.a);Z(iQ,this.a);Z(jQ,this.a);Z(kQ,this.a);Z(lQ,this.a);TP(this,VP);nL(this);a=this.j;VL(this.lc.c,a.a,a.b);!sx(this)&&RK(this);MK(this)}q(593,575,KH,SP);
_.kg=function(a,b){var c;H(b,CP)?(qQ(this),TP(this,VP),UP(this)):C(a.f,89)?(tQ(this),Dr(a.f)===Dr(VP)?(rQ(this),sQ(this)):Dr(a.f)===Dr(WP)?(rQ(this),sQ(this)):Dr(a.f)===Dr(XP)?(rQ(this),sQ(this)):Dr(a.f)===Dr(iQ)?Z(jQ,this.a):Dr(a.f)===Dr(jQ)?(Z(iQ,this.a),Z(bQ,this.a)):Dr(a.f)===Dr(bQ)?(Z(cQ,this.a),Z(jQ,this.a)):Dr(a.f)===Dr(cQ)?Z(bQ,this.a):Dr(a.f)===Dr(mQ)||Dr(a.f)===Dr(nQ)||Dr(a.f)===Dr(oQ)||Dr(a.f)===Dr(pQ)?(qQ(this),this.b=!0):sQ(this),TP(this,a.f),UP(this)):C(a.f,90)&&(tQ(this),c=a.f,0==c.lc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(py(),yy)),UP(this));107!=this.c.e&&(this.c.e=107,by(this.c));return!0};_.lg=function(){return Nm(this.e.lc.a.ob,Ig)};_.mg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var VP=_.e=null,mQ=null,WP=null,bQ=null,nQ=null,$P=null,dQ=null,lQ=null,kQ=null,ZP=null,YP=null,XP=null,aQ=null,eQ=null,cQ=null,jQ=null,pQ=null,fQ=null,hQ=null,iQ=null,oQ=null,gQ=null;function PP(a){RG();TG.call(this);this.a=new LP;du(this.a,new uQ(this,a),(GP(),GP(),HP))}q(639,637,{},PP);_.Ne=function(){return this.a};
_.a=null;function uQ(a,b){this.a=a;this.b=b}q(640,1,{},uQ);_.a=null;_.b=null;X(593);X(428);X(639);X(640);X(361);X(215);x(GH)(3);