var RP="3",SP="Any",TP="Aromatic",UP="Nonring",VP="Reset",YP="Ring";function ZP(){ZP=r;$P=new wp(Tc,new aQ)}function aQ(){}q(217,214,{},aQ);_.Sc=function(a){Vx();rM(this,a.b,bQ(a.a.a,a.a.a.ob.selectedIndex))};_.Vc=function(){return $P};var $P;function cQ(a,b){if(0>b||b>=a.ob.options.length)throw new Qu;}function bQ(a,b){cQ(a,b);return a.ob.options[b].value}function dQ(){this.ob=$doc.createElement("select");this.ob[Vc]="gwt-ListBox"}q(364,342,Vh,dQ);function eQ(){eQ=r}
function fQ(a,b){if(null==b)throw new or("Missing message: awt.103");var c=-1,d,e,f;f=a.lc.a.ob;e=$doc.createElement(nf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function gQ(){eQ();Ux.call(this);new yi;this.lc=new hQ((Vx(),this))}q(432,419,{91:1,93:1,100:1,112:1,118:1},gQ);_.de=function(){return Zx(this.lc,this)};
_.se=function(){return(null==this.ic&&(this.ic=Gx(this)),this.ic)+xa+this.tc+xa+this.uc+xa+this.qc+Lg+this.gc+(this.pc?j:",hidden")+",current="+bQ(this.lc.a,this.lc.a.ob.selectedIndex)};function iQ(){QL.call(this,7)}q(445,1,fi,iQ);function jQ(a){SL.call(this,a,0)}q(450,419,Sh,jQ);q(587,585,Ah);_.Oc=function(){!this.a.Hb?this.a.Hb=new kQ(this.a):this.a.Hb.lc.c.gb?fN(this.a.Hb.lc.c):mM(this.a.Hb)};function lQ(a,b){bL(b)==a.a?Z(b,(Fy(),Oy)):Z(b,a.a)}
function mQ(a){var b,c,d,e;e=j;d=!1;bL(nQ)!=a.a?(e=va,d=!0):bL(oQ)!=a.a?(e="!#6",d=!0):bL(pQ)!=a.a?(Z(qQ,(Fy(),Oy)),Z(rQ,Oy),Z(sQ,Oy),Z(tQ,Oy),e="F,Cl,Br,I"):(b=bL(uQ)!=a.a,c=bL(vQ)!=a.a,bL(wQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),bL(xQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),bL(yQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),bL(zQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),bL(AQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),bL(qQ)!=a.a&&(e+="F,"),bL(rQ)!=a.a&&(e+="Cl,"),bL(sQ)!=a.a&&(e+="Br,"),bL(tQ)!=a.a&&(e+="I,"),
XE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=oc:c?e=rb:(Z(nQ,(Fy(),Oy)),e=va)));b=j;d&&bL(uQ)!=a.a&&(b+=";a");d&&bL(vQ)!=a.a&&(b+=";A");bL(BQ)!=a.a&&(b+=";R");bL(CQ)!=a.a&&(b+=";!R");bL(nQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=DQ.lc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=EQ.lc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);bL(FQ)!=a.a&&(e="~");bL(GQ)!=a.a&&(e=hb);bL(HQ)!=a.a&&(e=qb);bL(IQ)!=a.a&&(e="!@");Lz(a.e.lc,e)}
function JQ(a){KQ(a);LQ(a);var b=DQ.lc.a;cQ(b,0);b.ob.options[0].selected=!0;b=EQ.lc.a;cQ(b,0);b.ob.options[0].selected=!0;Z(uQ,a.a);Z(vQ,a.a);Z(BQ,a.a);Z(CQ,a.a);Z(DQ,a.a);Z(EQ,a.a);MQ(a)}function KQ(a){Z(wQ,a.a);Z(xQ,a.a);Z(yQ,a.a);Z(zQ,a.a);Z(AQ,a.a);Z(qQ,a.a);Z(rQ,a.a);Z(sQ,a.a);Z(tQ,a.a)}function LQ(a){Z(nQ,a.a);Z(oQ,a.a);Z(pQ,a.a)}function MQ(a){Z(FQ,a.a);Z(GQ,a.a);Z(HQ,a.a);Z(IQ,a.a);a.b=!1}
function kQ(a){JL.call(this,"Atom/Bond Query");this.i=new CL(this.ig());yy(this.q,new pM(this));this.a=(bB(),dB);this.c=a;this.d||(a=Jx(a),this.d=new UL(a),lM(this.d,-150,10));this.j=this.d;hy(this,new iQ);Z(this,this.a);a=new my;hy(a,new ez(0,3,1));$(a,new jQ("Atom type :"),null);nQ=new CL(SP);oQ=new CL("Any except C");pQ=new CL("Halogen");$(a,nQ,null);$(a,oQ,null);$(a,pQ,null);$(this,a,null);a=new my;hy(a,new ez(0,3,1));$(a,new SL("Or select one or more from the list :",0),null);$(this,a,null);
a=new my;hy(a,new ez(0,3,1));wQ=new CL(vb);xQ=new CL(Rb);yQ=new CL(Vb);zQ=new CL(bc);AQ=new CL(Wb);qQ=new CL(Eb);rQ=new CL(yb);sQ=new CL(ub);tQ=new CL(Kb);$(a,wQ,null);$(a,xQ,null);$(a,yQ,null);$(a,zQ,null);$(a,AQ,null);$(a,qQ,null);$(a,rQ,null);$(a,sQ,null);$(a,tQ,null);$(this,a,null);a=new my;hy(a,new ez(0,3,1));DQ=new gQ;fQ(DQ,SP);fQ(DQ,$a);fQ(DQ,bb);fQ(DQ,gb);fQ(DQ,RP);$(a,new jQ("Number of hydrogens :  "),null);$(a,DQ,null);$(this,a,null);a=new my;hy(a,new ez(0,3,1));EQ=new gQ;fQ(EQ,SP);fQ(EQ,
$a);fQ(EQ,bb);fQ(EQ,gb);fQ(EQ,RP);fQ(EQ,"4");fQ(EQ,"5");fQ(EQ,"6");$(a,new SL("Number of connections :",0),null);$(a,EQ,null);$(a,new SL(" (H's don't count.)",0),null);$(this,a,null);a=new my;hy(a,new ez(0,3,1));$(a,new jQ("Atom is :"),null);uQ=new CL(TP);$(a,uQ,null);vQ=new CL("Nonaromatic");$(a,vQ,null);BQ=new CL(YP);$(a,BQ,null);CQ=new CL(UP);$(a,CQ,null);$(this,a,null);a=new my;Z(a,Vy(bL(this)));hy(a,new ez(0,3,1));$(a,new jQ("Bond is :"),null);FQ=new CL(SP);$(a,FQ,null);GQ=new CL(TP);$(a,GQ,
null);HQ=new CL(YP);$(a,HQ,null);IQ=new CL(UP);$(a,IQ,null);$(this,a,null);a=new my;hy(a,new ez(1,3,1));this.e=new Kz(va,20);$(a,this.e,null);$(a,new CL(VP),null);$(a,this.i,null);$(this,a,null);this.lc&&LL(this.lc.c,!1);IL(this,!1);KQ(this);LQ(this);MQ(this);Z(uQ,this.a);Z(vQ,this.a);Z(BQ,this.a);Z(CQ,this.a);Z(DQ,this.a);Z(EQ,this.a);lQ(this,nQ);HL(this);a=this.j;nM(this.lc.c,a.a,a.b);!Ix(this)&&kL(this);fL(this)}q(597,579,ZH,kQ);
_.jg=function(a,b){var c;H(b,VP)?(JQ(this),lQ(this,nQ),mQ(this)):C(a.f,90)?(MQ(this),Wr(a.f)===Wr(nQ)?(KQ(this),LQ(this)):Wr(a.f)===Wr(oQ)?(KQ(this),LQ(this)):Wr(a.f)===Wr(pQ)?(KQ(this),LQ(this)):Wr(a.f)===Wr(BQ)?Z(CQ,this.a):Wr(a.f)===Wr(CQ)?(Z(BQ,this.a),Z(uQ,this.a)):Wr(a.f)===Wr(uQ)?(Z(vQ,this.a),Z(CQ,this.a)):Wr(a.f)===Wr(vQ)?Z(uQ,this.a):Wr(a.f)===Wr(FQ)||Wr(a.f)===Wr(GQ)||Wr(a.f)===Wr(HQ)||Wr(a.f)===Wr(IQ)?(JQ(this),this.b=!0):LQ(this),lQ(this,a.f),mQ(this)):C(a.f,91)&&(MQ(this),c=a.f,0==c.lc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Fy(),Oy)),mQ(this));107!=this.c.e&&(this.c.e=107,ry(this.c));return!0};_.kg=function(){return Qm(this.e.lc.a.ob,Fg)};_.lg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var nQ=_.e=null,FQ=null,oQ=null,uQ=null,GQ=null,sQ=null,wQ=null,EQ=null,DQ=null,rQ=null,qQ=null,pQ=null,tQ=null,xQ=null,vQ=null,CQ=null,IQ=null,yQ=null,AQ=null,BQ=null,HQ=null,zQ=null;function hQ(a){fH();hH.call(this);this.a=new dQ;xu(this.a,new NQ(this,a),(ZP(),ZP(),$P))}q(643,641,{},hQ);_.Me=function(){return this.a};
_.a=null;function NQ(a,b){this.a=a;this.b=b}q(644,1,{},NQ);_.a=null;_.b=null;X(597);X(432);X(643);X(644);X(364);X(217);x(WH)(3);