var JZ=" (H's don't count.)",KZ="!#6",LZ="!@",MZ="#15,",NZ="#16,",OZ="#6,",PZ="#7,",QZ="#8,",RZ="3",SZ="4",TZ="5",UZ="6",VZ=";!R",WZ=";A",XZ=";D",YZ=";H",ZZ=";R",$Z=";a",a_="<SELECT>",b_="Any",c_="Any except C",d_="Aromatic",e_="Atom is :",f_="Atom type :",g_="Atom/Bond Query",h_="Bond is :",i_="Br,",j_="C,",k_="Cl,",l_="F,",m_="F,Cl,Br,I",n_="Halogen",o_="I,",p_="Missing message: awt.103",q_="N,",r_="Nonaromatic",s_="Nonring",t_="Number of connections :",u_="Number of hydrogens :  ",v_="O,",w_="Or select one or more from the list :",
x_="P,",y_="Reset",z_="Ring",A_="S,",B_="bidiwrapped",C_="c,",D_="gwt-ListBox",E_="n,",F_="o,",G_="p,",H_="s,",I_="~";function J_(){J_=s;K_=new Jx(vj,new L_)}function L_(){}r(193,190,{},L_);_.Oc=function(a){dF();aW(this,a.b,M_(a.a.a,a.a.a.ob.selectedIndex))};_.Rc=function(){return K_};var K_;function N_(a,b){if(0>b||b>=a.ob.options.length)throw new iC;}function M_(a,b){N_(a,b);return a.ob.options[b].value}function O_(){var a;this.ob=(a=a_,$doc.createElement(a));this.ob[Aj]=D_}r(341,319,jr,O_);
function P_(){P_=s}function Q_(a,b){if(null==b)throw new jz(p_);var c=-1,d,e,f;f=a.lc.a.ob;e=H(Kn);e.text=b;e.removeAttribute(B_);e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e):(c=f.options[c])?f.add(e,c.index):f.add(e)}function R_(){P_();cF.call(this);new $r;this.lc=new S_((dF(),this))}r(410,397,{89:1,91:1,98:1,110:1,116:1},R_);_._d=function(){return hF(this.lc,this)};
_.oe=function(){return(null==this.ic&&(this.ic=PE(this)),this.ic)+hb+this.tc+hb+this.uc+hb+this.qc+sq+this.gc+(this.pc?l:",hidden")+",current="+M_(this.lc.a,this.lc.a.ob.selectedIndex)};function T_(){zV.call(this,7)}r(423,1,fr,T_);function U_(a){BV.call(this,a,0)}r(428,397,Er,U_);r(554,552,vr);_.Kc=function(){!this.a.Hb?this.a.Hb=new V_(this.a):this.a.Hb.lc.c.gb?PW(this.a.Hb.lc.c):WV(this.a.Hb)};function W_(a,b){LU(b)==a.a?Z(b,(NF(),WF)):Z(b,a.a)}
function X_(a){var b,c,d,e;e=l;d=!1;LU(Y_)!=a.a?(e=fb,d=!0):LU(Z_)!=a.a?(e=KZ,d=!0):LU($_)!=a.a?(Z(a0,(NF(),WF)),Z(b0,WF),Z(c0,WF),Z(d0,WF),e=m_):(b=LU(e0)!=a.a,c=LU(f0)!=a.a,LU(g0)!=a.a&&(b?e+=C_:c?e+=j_:e+=OZ),LU(h0)!=a.a&&(b?e+=E_:c?e+=q_:e+=PZ),LU(i0)!=a.a&&(b?e+=F_:c?e+=v_:e+=QZ),LU(j0)!=a.a&&(b?e+=H_:c?e+=A_:e+=NZ),LU(k0)!=a.a&&(b?e+=G_:c?e+=x_:e+=MZ),LU(a0)!=a.a&&(e+=l_),LU(b0)!=a.a&&(e+=k_),LU(c0)!=a.a&&(e+=i_),LU(d0)!=a.a&&(e+=o_),bM(e,hb)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&
(b?e=yi:c?e=Qc:(Z(Y_,(NF(),WF)),e=fb)));b=l;d&&LU(e0)!=a.a&&(b+=$Z);d&&LU(f0)!=a.a&&(b+=WZ);LU(l0)!=a.a&&(b+=ZZ);LU(m0)!=a.a&&(b+=VZ);LU(Y_)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=n0.lc.a.ob.selectedIndex;0<d&&(--d,e+=YZ+d);d=o0.lc.a.ob.selectedIndex;0<d&&(--d,e+=XZ+d);LU(p0)!=a.a&&(e=I_);LU(q0)!=a.a&&(e=oc);LU(r0)!=a.a&&(e=Ic);LU(s0)!=a.a&&(e=LZ);TG(a.e.lc,e)}
function t0(a){u0(a);v0(a);var b=n0.lc.a;N_(b,0);b.ob.options[0].selected=!0;b=o0.lc.a;N_(b,0);b.ob.options[0].selected=!0;Z(e0,a.a);Z(f0,a.a);Z(l0,a.a);Z(m0,a.a);Z(n0,a.a);Z(o0,a.a);w0(a)}function u0(a){Z(g0,a.a);Z(h0,a.a);Z(i0,a.a);Z(j0,a.a);Z(k0,a.a);Z(a0,a.a);Z(b0,a.a);Z(c0,a.a);Z(d0,a.a)}function v0(a){Z(Y_,a.a);Z(Z_,a.a);Z($_,a.a)}function w0(a){Z(p0,a.a);Z(q0,a.a);Z(r0,a.a);Z(s0,a.a);a.b=!1}
function V_(a){sV.call(this,g_);this.i=new lV(this.cg());GF(this.q,new ZV(this));this.a=(eI(),gI);this.c=a;this.d||(a=SE(a),this.d=new DV(a),VV(this.d,-150,10));this.j=this.d;pF(this,new T_);Z(this,this.a);a=new uF;pF(a,new mG(0,3,1));$(a,new U_(f_),null);Y_=new lV(b_);Z_=new lV(c_);$_=new lV(n_);$(a,Y_,null);$(a,Z_,null);$(a,$_,null);$(this,a,null);a=new uF;pF(a,new mG(0,3,1));$(a,new BV(w_,0),null);$(this,a,null);a=new uF;pF(a,new mG(0,3,1));g0=new lV(id);h0=new lV(vf);i0=new lV(Nf);j0=new lV(cg);
k0=new lV(Qf);a0=new lV(ke);b0=new lV(Cd);c0=new lV(hd);d0=new lV(ve);$(a,g0,null);$(a,h0,null);$(a,i0,null);$(a,j0,null);$(a,k0,null);$(a,a0,null);$(a,b0,null);$(a,c0,null);$(a,d0,null);$(this,a,null);a=new uF;pF(a,new mG(0,3,1));n0=new R_;Q_(n0,b_);Q_(n0,$b);Q_(n0,cc);Q_(n0,hc);Q_(n0,RZ);$(a,new U_(u_),null);$(a,n0,null);$(this,a,null);a=new uF;pF(a,new mG(0,3,1));o0=new R_;Q_(o0,b_);Q_(o0,$b);Q_(o0,cc);Q_(o0,hc);Q_(o0,RZ);Q_(o0,SZ);Q_(o0,TZ);Q_(o0,UZ);$(a,new BV(t_,0),null);$(a,o0,null);$(a,new BV(JZ,
0),null);$(this,a,null);a=new uF;pF(a,new mG(0,3,1));$(a,new U_(e_),null);e0=new lV(d_);$(a,e0,null);f0=new lV(r_);$(a,f0,null);l0=new lV(z_);$(a,l0,null);m0=new lV(s_);$(a,m0,null);$(this,a,null);a=new uF;Z(a,cG(LU(this)));pF(a,new mG(0,3,1));$(a,new U_(h_),null);p0=new lV(b_);$(a,p0,null);q0=new lV(d_);$(a,q0,null);r0=new lV(z_);$(a,r0,null);s0=new lV(s_);$(a,s0,null);$(this,a,null);a=new uF;pF(a,new mG(1,3,1));this.e=new SG(fb,20);$(a,this.e,null);$(a,new lV(y_),null);$(a,this.i,null);$(this,a,
null);this.lc&&uV(this.lc.c,!1);rV(this,!1);u0(this);v0(this);w0(this);Z(e0,this.a);Z(f0,this.a);Z(l0,this.a);Z(m0,this.a);Z(n0,this.a);Z(o0,this.a);W_(this,Y_);qV(this);a=this.j;XV(this.lc.c,a.a,a.b);!RE(this)&&UU(this);PU(this)}r(564,546,jP,V_);
_.dg=function(a,b){var c;L(b,y_)?(t0(this),W_(this,Y_),X_(this)):D(a.f,88)?(w0(this),Rz(a.f)===Rz(Y_)?(u0(this),v0(this)):Rz(a.f)===Rz(Z_)?(u0(this),v0(this)):Rz(a.f)===Rz($_)?(u0(this),v0(this)):Rz(a.f)===Rz(l0)?Z(m0,this.a):Rz(a.f)===Rz(m0)?(Z(l0,this.a),Z(e0,this.a)):Rz(a.f)===Rz(e0)?(Z(f0,this.a),Z(m0,this.a)):Rz(a.f)===Rz(f0)?Z(e0,this.a):Rz(a.f)===Rz(p0)||Rz(a.f)===Rz(q0)||Rz(a.f)===Rz(r0)||Rz(a.f)===Rz(s0)?(t0(this),this.b=!0):v0(this),W_(this,a.f),X_(this)):D(a.f,89)&&(w0(this),c=a.f,0==c.lc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(NF(),WF)),X_(this));107!=this.c.e&&(this.c.e=107,zF(this.c));return!0};_.eg=function(){return jw(this.e.lc.a.ob,fq)};_.fg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var Y_=_.e=null,p0=null,Z_=null,e0=null,q0=null,c0=null,g0=null,o0=null,n0=null,b0=null,a0=null,$_=null,d0=null,h0=null,f0=null,m0=null,s0=null,i0=null,k0=null,l0=null,r0=null,j0=null;function S_(a){oO();qO.call(this);this.a=new O_;QB(this.a,new x0(this,a),(J_(),J_(),K_))}r(609,607,{},S_);_.Ie=function(){return this.a};
_.a=null;function x0(a,b){this.a=a;this.b=b}r(610,1,{},x0);_.a=null;_.b=null;Y(564);Y(410);Y(609);Y(610);Y(341);Y(193);y(cP)(3);